-- RawDrop catalog + admin schema (products, sections, site settings, admin auth)
-- Replaces the local JSON file store (data/store.json), which cannot persist on Cloudflare Workers.

CREATE TABLE IF NOT EXISTS sections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  image_url TEXT NOT NULL DEFAULT '',
  section_id INTEGER NOT NULL REFERENCES sections (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_section_id ON products (section_id);

CREATE TABLE IF NOT EXISTS site_settings (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  store_name TEXT NOT NULL DEFAULT 'RawDrop',
  tagline TEXT NOT NULL DEFAULT '',
  products_page_title TEXT NOT NULL DEFAULT '',
  products_page_subtitle TEXT NOT NULL DEFAULT '',
  footer_text TEXT NOT NULL DEFAULT '',
  hero_title TEXT NOT NULL DEFAULT '',
  hero_subtitle TEXT NOT NULL DEFAULT '',
  hero_button_text TEXT NOT NULL DEFAULT '',
  hero_image_url TEXT NOT NULL DEFAULT '',
  about_title TEXT NOT NULL DEFAULT '',
  about_text TEXT NOT NULL DEFAULT '',
  contact_email TEXT NOT NULL DEFAULT '',
  contact_phone TEXT NOT NULL DEFAULT '',
  testimonial_1_name TEXT NOT NULL DEFAULT '',
  testimonial_1_text TEXT NOT NULL DEFAULT '',
  testimonial_2_name TEXT NOT NULL DEFAULT '',
  testimonial_2_text TEXT NOT NULL DEFAULT '',
  testimonial_3_name TEXT NOT NULL DEFAULT '',
  testimonial_3_text TEXT NOT NULL DEFAULT '',
  btc_wallet_address TEXT NOT NULL DEFAULT '',
  btc_payment_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_users (
  username TEXT PRIMARY KEY,
  password_hash TEXT NOT NULL
);

ALTER TABLE sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
-- No policies defined: only the service_role key (used server-side) can read/write these
-- tables; the anon/publishable key gets zero access since RLS defaults to deny-all.

-- Seed: sections
INSERT INTO sections (id, name, sort_order) VALUES
  (1, 'Cactus', 1),
  (2, 'Best Sellers', 2),
  (3, 'Electronics', 3),
  (4, 'Fashion & Apparel', 4),
  (5, 'Home & Living', 5),
  (6, 'Beauty & Personal Care', 6),
  (7, 'Sports & Outdoors', 7),
  (8, 'Accessories', 8),
  (9, 'Clearance & Special Offers', 9)
ON CONFLICT (id) DO NOTHING;

-- Seed: products
INSERT INTO products (id, name, slug, description, price, image_url, section_id, created_at) VALUES
  (1, 'Essential Cotton Tee — White', 'essential-cotton-tee-white-1', 'A wardrobe staple crafted from soft, breathable cotton. Relaxed fit with reinforced stitching for everyday wear. Machine washable. Available for customization in your dashboard.', 200, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop', 1, '2026-07-02T13:02:30.292Z'),
  (2, 'Slim Fit Denim Jacket', 'slim-fit-denim-jacket-2', 'Classic denim jacket with a modern slim silhouette. Durable wash, metal hardware, and functional chest pockets. Layer over any outfit for a polished casual look.', 200, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop', 1, '2026-07-02T13:02:30.294Z'),
  (3, 'Minimalist Watch — Silver', 'minimalist-watch-silver-3', 'Clean analog design with a stainless steel case and adjustable link band. Water-resistant for daily use. Includes presentation box — ideal for gifting.', 200, 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop', 1, '2026-07-02T13:02:30.294Z'),
  (4, 'Everyday Crossbody Bag', 'everyday-crossbody-bag-4', 'Compact crossbody with adjustable strap, interior zip pocket, and secure magnetic closure. Fits phone, wallet, and essentials. Lightweight for all-day carry.', 200, 'https://images.unsplash.com/photo-1560343090-f0409e92703a?w=600&h=600&fit=crop', 1, '2026-07-02T13:02:30.294Z'),
  (5, 'Performance Running Cap', 'performance-running-cap-5', 'Lightweight cap with moisture-wicking fabric and adjustable back strap. UV protection for outdoor training. One size fits most.', 200, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop', 1, '2026-07-02T13:02:30.294Z'),
  (6, 'Wireless Earbuds Pro', 'wireless-earbuds-pro-6', 'True wireless earbuds with active noise cancellation, 24-hour battery life with case, and touch controls. Includes three ear tip sizes for a secure fit.', 200, 'https://images.unsplash.com/photo-1546868871-7041f69a55b0?w=600&h=600&fit=crop', 2, '2026-07-02T13:02:30.294Z'),
  (7, 'Insulated Water Bottle — 32oz', 'insulated-water-bottle-32oz-7', 'Double-wall vacuum insulation keeps drinks cold 24 hours or hot 12 hours. BPA-free stainless steel, leak-proof lid, fits standard cup holders.', 200, 'https://images.unsplash.com/photo-1585386959984-a41552231654?w=600&h=600&fit=crop', 2, '2026-07-02T13:02:30.294Z'),
  (8, 'Organic Face Moisturizer', 'organic-face-moisturizer-8', 'Daily moisturizer with hyaluronic acid and vitamin E. Lightweight, non-greasy formula suitable for all skin types. Dermatologist tested, fragrance-free.', 200, 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=600&h=600&fit=crop', 2, '2026-07-02T13:02:30.294Z'),
  (9, 'Leather Belt — Brown', 'leather-belt-brown-9', 'Full-grain leather belt with brushed nickel buckle. 1.25-inch width, suitable for casual and business attire. Available in standard waist sizes.', 200, 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop', 2, '2026-07-02T13:02:30.294Z'),
  (10, 'Portable Phone Charger 10K', 'portable-phone-charger-10k-10', '10,000mAh power bank with USB-C and USB-A outputs. Fast-charge compatible. LED indicator shows remaining power. TSA-approved for travel.', 200, 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=600&fit=crop', 2, '2026-07-02T13:02:30.294Z'),
  (11, 'Bluetooth Speaker — Outdoor', 'bluetooth-speaker-outdoor-11', 'Rugged wireless speaker with 360° sound and 12-hour playtime. IPX7 waterproof rating. Built-in microphone for hands-free calls.', 200, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop', 3, '2026-07-02T13:02:30.294Z'),
  (12, 'USB-C Hub — 7-in-1', 'usb-c-hub-7-in-1-12', 'Expand your laptop with HDMI, USB 3.0, SD card reader, and 100W pass-through charging. Aluminum body, plug-and-play — no drivers required.', 200, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop', 3, '2026-07-02T13:02:30.294Z'),
  (13, 'Smart LED Desk Lamp', 'smart-led-desk-lamp-13', 'Adjustable arm lamp with five brightness levels and three color temperatures. Touch controls, memory function, and energy-efficient LED panel.', 200, 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop', 3, '2026-07-02T13:02:30.294Z'),
  (14, 'Mechanical Keyboard — Compact', 'mechanical-keyboard-compact-14', '75% layout mechanical keyboard with hot-swappable switches and RGB backlight. PBT keycaps, USB-C connection. Ideal for work and gaming.', 200, 'https://images.unsplash.com/photo-1560343090-f0409e92703a?w=600&h=600&fit=crop', 3, '2026-07-02T13:02:30.294Z'),
  (15, '4K Action Camera', '4k-action-camera-15', 'Capture adventures in 4K at 30fps with electronic image stabilization. Waterproof case included. Wi-Fi transfer to smartphone app.', 200, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop', 3, '2026-07-02T13:02:30.294Z'),
  (16, 'Merino Wool Sweater — Navy', 'merino-wool-sweater-navy-16', 'Fine merino wool pullover that''s naturally temperature-regulating and odor-resistant. Ribbed cuffs and hem. Machine wash cold on gentle cycle.', 200, 'https://images.unsplash.com/photo-1546868871-7041f69a55b0?w=600&h=600&fit=crop', 4, '2026-07-02T13:02:30.294Z'),
  (17, 'Classic Chino Pants — Khaki', 'classic-chino-pants-khaki-17', 'Tailored chinos in stretch cotton twill. Mid-rise fit with slant pockets and welt back pockets. Versatile for office or weekend.', 200, 'https://images.unsplash.com/photo-1585386959984-a41552231654?w=600&h=600&fit=crop', 4, '2026-07-02T13:02:30.294Z'),
  (18, 'Canvas Low-Top Sneakers', 'canvas-low-top-sneakers-18', 'Timeless canvas sneakers with cushioned insole and vulcanized rubber sole. Lace-up closure. Pairs with jeans, shorts, or casual dresses.', 200, 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=600&h=600&fit=crop', 4, '2026-07-02T13:02:30.294Z'),
  (19, 'Polarized Sunglasses — Aviator', 'polarized-sunglasses-aviator-19', 'UV400 polarized lenses reduce glare and protect eyes. Lightweight metal frame with adjustable nose pads. Includes hard case and cleaning cloth.', 200, 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop', 4, '2026-07-02T13:02:30.294Z'),
  (20, 'Wool Blend Scarf — Charcoal', 'wool-blend-scarf-charcoal-20', 'Soft wool-acrylic blend scarf for cold weather. Generous length for multiple wrap styles. Fringed edges. Dry clean recommended.', 200, 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=600&fit=crop', 4, '2026-07-02T13:02:30.294Z'),
  (21, 'Ceramic Dinnerware Set — 16pc', 'ceramic-dinnerware-set-16pc-21', 'Service for four including dinner plates, salad plates, bowls, and mugs. Microwave and dishwasher safe. Modern matte glaze finish.', 200, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop', 5, '2026-07-02T13:02:30.294Z'),
  (22, 'Memory Foam Pillow', 'memory-foam-pillow-22', 'Contoured memory foam pillow supports neck alignment for side and back sleepers. Removable, washable bamboo-derived cover. CertiPUR-US certified foam.', 200, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop', 5, '2026-07-02T13:02:30.294Z'),
  (23, 'Scented Candle — Lavender', 'scented-candle-lavender-23', 'Hand-poured soy wax candle with cotton wick. Approximately 45-hour burn time. Natural lavender essential oil blend. Reusable glass jar.', 200, 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop', 5, '2026-07-02T13:02:30.294Z'),
  (24, 'Throw Blanket — Knit', 'throw-blanket-knit-24', 'Chunky knit throw blanket in soft acrylic yarn. 50×60 inches — perfect for sofas and beds. Machine washable. Adds warmth and texture to any room.', 200, 'https://images.unsplash.com/photo-1560343090-f0409e92703a?w=600&h=600&fit=crop', 5, '2026-07-02T13:02:30.294Z'),
  (25, 'Stainless Steel Cookware Set', 'stainless-steel-cookware-set-25', 'Three-piece set: 8-inch fry pan, 2-quart saucepan with lid, and 6-quart stockpot with lid. Tri-ply construction for even heating. Oven safe to 500°F.', 200, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop', 5, '2026-07-02T13:02:30.294Z'),
  (26, 'Vitamin C Serum — 1oz', 'vitamin-c-serum-1oz-26', 'Brightening serum with 15% L-ascorbic acid and ferulic acid. Apply morning before moisturizer and SPF. Visible results in 4–6 weeks with consistent use.', 200, 'https://images.unsplash.com/photo-1546868871-7041f69a55b0?w=600&h=600&fit=crop', 6, '2026-07-02T13:02:30.294Z'),
  (27, 'Electric Toothbrush Kit', 'electric-toothbrush-kit-27', 'Sonic toothbrush with two-minute timer and three cleaning modes. Includes charging base and two replacement heads. ADA accepted.', 200, 'https://images.unsplash.com/photo-1585386959984-a41552231654?w=600&h=600&fit=crop', 6, '2026-07-02T13:02:30.294Z'),
  (28, 'Hair Styling Clay — Matte', 'hair-styling-clay-matte-28', 'Medium-hold matte clay for textured, natural-looking styles. Water-based formula washes out easily. Works on short to medium hair lengths.', 200, 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=600&h=600&fit=crop', 6, '2026-07-02T13:02:30.294Z'),
  (29, 'Body Wash — Eucalyptus', 'body-wash-eucalyptus-29', 'Plant-derived body wash with eucalyptus and mint. Sulfate-free, gentle on skin. Large 16oz bottle with pump dispenser.', 200, 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop', 6, '2026-07-02T13:02:30.294Z'),
  (30, 'Grooming Kit — Travel', 'grooming-kit-travel-30', 'TSA-friendly grooming set: nail clipper, tweezers, scissors, and comb in a zippered leather case. Essential tools for travel or daily use.', 200, 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=600&fit=crop', 6, '2026-07-02T13:02:30.294Z'),
  (31, 'Yoga Mat — 6mm Extra Thick', 'yoga-mat-6mm-extra-thick-31', 'Non-slip TPE yoga mat with carrying strap. 6mm cushioning protects joints during floor work. Free of latex, PVC, and phthalates.', 150, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop', 7, '2026-07-02T13:02:30.294Z'),
  (32, 'Resistance Bands Set', 'resistance-bands-set-32', 'Five color-coded bands from light to heavy resistance. Includes door anchor, handles, and ankle straps. Full-body workout guide included.', 150, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop', 7, '2026-07-02T13:02:30.294Z'),
  (33, 'Camping Headlamp — Rechargeable', 'camping-headlamp-rechargeable-33', 'LED headlamp with 300-lumen max output and red night-vision mode. USB rechargeable, 40-hour runtime on low. IPX4 splash resistant.', 150, 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop', 7, '2026-07-02T13:02:30.294Z'),
  (34, 'Stainless Steel Flask — 8oz', 'stainless-steel-flask-8oz-34', 'Vacuum-insulated flask keeps beverages hot or cold for hours. Leak-proof cap, slim profile fits pockets and bags. Food-grade 18/8 steel.', 150, 'https://images.unsplash.com/photo-1560343090-f0409e92703a?w=600&h=600&fit=crop', 7, '2026-07-02T13:02:30.294Z'),
  (35, 'Fitness Tracker Band', 'fitness-tracker-band-35', 'Tracks steps, heart rate, sleep, and workouts. 7-day battery life. Syncs with iOS and Android. Water resistant for swimming and showers.', 150, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop', 7, '2026-07-02T13:02:30.294Z'),
  (36, 'Leather Wallet — Bifold', 'leather-wallet-bifold-36', 'Genuine leather bifold with six card slots and bill compartment. RFID-blocking lining protects against digital theft. Slim profile fits front pocket.', 150, 'https://images.unsplash.com/photo-1546868871-7041f69a55b0?w=600&h=600&fit=crop', 8, '2026-07-02T13:02:30.294Z'),
  (37, 'Travel Duffel Bag — 40L', 'travel-duffel-bag-40l-37', 'Durable canvas duffel with reinforced handles and removable shoulder strap. Interior zip pocket. Fits overhead bin requirements on most airlines.', 150, 'https://images.unsplash.com/photo-1585386959984-a41552231654?w=600&h=600&fit=crop', 8, '2026-07-02T13:02:30.294Z'),
  (38, 'Silk Tie — Navy Paisley', 'silk-tie-navy-paisley-38', '100% silk tie with classic paisley pattern. 3.25-inch blade width. Hand-finished edges. Perfect for business and formal occasions.', 150, 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=600&h=600&fit=crop', 8, '2026-07-02T13:02:30.294Z'),
  (39, 'Key Organizer — Leather', 'key-organizer-leather-39', 'Hold up to six keys in a compact leather holder. Eliminates pocket bulk and key jingle. Expandable post accommodates most key types.', 150, 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop', 8, '2026-07-02T13:02:30.294Z'),
  (40, 'Laptop Sleeve — 15 inch', 'laptop-sleeve-15-inch-40', 'Padded neoprene sleeve protects laptops up to 15.6 inches. Slim design slides into backpacks and briefcases. Zippered front pocket for cables.', 150, 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=600&fit=crop', 8, '2026-07-02T13:02:30.294Z'),
  (41, 'Bundle — Skincare Starter Kit', 'bundle-skincare-starter-kit-41', 'Three-step skincare set: cleanser, toner, and moisturizer. Suitable for normal to combination skin. Save 20% compared to buying separately.', 200, 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (42, 'Bundle — Home Office Essentials', 'bundle-home-office-essentials-42', 'Desk organizer, mouse pad, and cable management kit. Everything needed to set up a clean, productive workspace at home.', 200, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (43, 'Open-Box — Smart Speaker', 'open-box-smart-speaker-43', 'Previous-generation smart speaker in open-box condition. Fully tested and functional. Voice assistant compatible. Minor packaging wear only.', 200, 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (44, 'Seasonal — Gift Set Box', 'seasonal-gift-set-box-44', 'Curated gift box with three customer-favorite items. Ready to wrap and give. Limited seasonal availability.', 200, 'https://images.unsplash.com/photo-1560343090-f0409e92703a?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (45, 'Refurbished — Tablet 10 inch', 'refurbished-tablet-10-inch-45', 'Certified refurbished tablet with 10-inch display, 64GB storage, and one-year warranty. Inspected and restored to factory standards.', 200, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (46, 'Limited Edition — Cap Collection', 'limited-edition-cap-collection-46', 'Exclusive cap design not available in standard catalog. Embroidered logo, adjustable strap. Once sold out, will not be restocked.', 200, 'https://images.unsplash.com/photo-1546868871-7041f69a55b0?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (47, 'Outlet — Classic Polo Shirt', 'outlet-classic-polo-shirt-47', 'End-of-season polo in pique cotton. Side vents and ribbed collar. Final sale pricing while supplies last.', 200, 'https://images.unsplash.com/photo-1585386959984-a41552231654?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (48, 'Outlet — Canvas Tote Bag', 'outlet-canvas-tote-bag-48', 'Heavy-duty canvas tote with interior pocket and reinforced handles. Ideal for groceries, gym, or daily errands. While supplies last.', 200, 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (49, 'Flash Deal — Earbud Case Cover', 'flash-deal-earbud-case-cover-49', 'Protective silicone case for popular earbud models. Anti-scratch, easy grip. Available in multiple colors while flash deal lasts.', 200, 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (50, 'Flash Deal — Phone Grip Stand', 'flash-deal-phone-grip-stand-50', 'Adhesive phone grip that doubles as a stand for video calls and media. Universal fit. Limited-time pricing.', 200, 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=600&fit=crop', 9, '2026-07-02T13:02:30.294Z'),
  (51, 'Checkout Test — $20', 'checkout-test-20-51', 'Payment gateway test product. Fixed $20 price — use this to verify checkout and NOWPayments without a large order.', 20, 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=600&fit=crop', 9, '2026-07-03T15:54:00.000Z')
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequences past the seeded ids so future admin-created rows do not collide
SELECT setval(pg_get_serial_sequence('sections', 'id'), (SELECT MAX(id) FROM sections));
SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));

-- Seed: site settings (singleton row)
INSERT INTO site_settings (
  id, store_name, tagline, products_page_title, products_page_subtitle, footer_text,
  hero_title, hero_subtitle, hero_button_text, hero_image_url, about_title, about_text,
  contact_email, contact_phone,
  testimonial_1_name, testimonial_1_text, testimonial_2_name, testimonial_2_text,
  testimonial_3_name, testimonial_3_text, btc_wallet_address, btc_payment_enabled
) VALUES (
  1, 'Local Shop', 'Premium products · $1,000 each', 'Shop All Products', '50 items organized in sections — edit everything from your dashboard', '© Local Shop. All rights reserved.',
  'Welcome to RawDrop', 'Clean catalog. Add to cart and checkout in seconds.', 'Shop Now', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1400&h=700&fit=crop', 'Why RawDrop', 'RawDrop keeps it simple — browse products, add to cart, and checkout. No hassle. Edit everything from your admin dashboard.',
  'orders@rawdrop.com', '+1 (555) 987-6543',
  'Marcus T.', 'Fast checkout, product on point. RawDrop is legit.', 'Jaylen K.', 'Easy to pick what I needed. Cart and checkout took 2 minutes.',
  'Destiny R.', 'Smooth experience. Already ordered twice.', '', false
)
ON CONFLICT (id) DO NOTHING;

-- Seed: admin login (preserves the existing bcrypt hash from data/store.json)
INSERT INTO admin_users (username, password_hash) VALUES ('admin', '$2a$10$JqZywX8td3nLMDShQbPeDOpNs5s42uy9N4nioyvrLC6EFxlq3KhmG')
ON CONFLICT (username) DO NOTHING;
