-- Adds a per-product long-form "Details" field, and makes the gram/button
-- pricing tiers (previously hardcoded in src/lib/pricing.ts) editable from
-- the dashboard's Site tab.

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS details TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE sections
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE site_settings
  ADD COLUMN IF NOT EXISTS gram_28g_label TEXT NOT NULL DEFAULT '28g',
  ADD COLUMN IF NOT EXISTS gram_28g_price NUMERIC(12, 2) NOT NULL DEFAULT 200,
  ADD COLUMN IF NOT EXISTS gram_qtr_label TEXT NOT NULL DEFAULT '1/4 lb (113g)',
  ADD COLUMN IF NOT EXISTS gram_qtr_price NUMERIC(12, 2) NOT NULL DEFAULT 250,
  ADD COLUMN IF NOT EXISTS gram_half_label TEXT NOT NULL DEFAULT '1/2 lb (227g)',
  ADD COLUMN IF NOT EXISTS gram_half_price NUMERIC(12, 2) NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS gram_1lb_label TEXT NOT NULL DEFAULT '1 lb (454g)',
  ADD COLUMN IF NOT EXISTS gram_1lb_price NUMERIC(12, 2) NOT NULL DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS button_8_label TEXT NOT NULL DEFAULT '8 buttons',
  ADD COLUMN IF NOT EXISTS button_8_price NUMERIC(12, 2) NOT NULL DEFAULT 150,
  ADD COLUMN IF NOT EXISTS button_16_label TEXT NOT NULL DEFAULT '16 buttons',
  ADD COLUMN IF NOT EXISTS button_16_price NUMERIC(12, 2) NOT NULL DEFAULT 280,
  ADD COLUMN IF NOT EXISTS button_32_label TEXT NOT NULL DEFAULT '32 buttons',
  ADD COLUMN IF NOT EXISTS button_32_price NUMERIC(12, 2) NOT NULL DEFAULT 540,
  ADD COLUMN IF NOT EXISTS button_64_label TEXT NOT NULL DEFAULT '64 buttons',
  ADD COLUMN IF NOT EXISTS button_64_price NUMERIC(12, 2) NOT NULL DEFAULT 1000;
